name: CI
on:
  pull_request:
  push:
    branches:
    - main
    paths-ignore:
      - '**/.md'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20

    - name: Instal libssl (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libssl-dev

    - name: Setup LLVM
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: 17

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "17.0"

    - name: llvm-config
      run: llvm-config --version --bindir --libdir

    - name: Install zstd (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install zstd
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, rust-src

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72
    
    - name: Test
      run: cargo test --verbose